version: "3.9"

services:

  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      - POSTGRES_DB=dev_mem
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    ports:
      - "45533:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev -d dev_mem" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


